### ISSUE TITLE
Potential problem during SEMSIM calculation with Information Content

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/semsimian#133] opened 2024-08-12 20:18 UTC
# Description
When analyzing a SEMSIM profile using the `--information-content` flag, all the `jaccard_similarity` values are coming out as zero. This seems incorrect given that the `--min-jaccard-similarity` is configured as `0.4`. Any records with a `jaccard_similarity` below this threshold should not be included in the output file. It's also worth noting that all records currently have a `jaccard_similarity` of 0 and `cosine_similarity`, `dice_similarity`, `phenodigm_score` are all `None`.

###  Command: 
```bash

runoak --stacktrace -vvv  -i semsimian:sqlite:data/ontology/phenio-monarch.db similarity -p i \
--set1-file data/tmp/hp_terms.txt \
--set2-file data/tmp/mp_terms.txt \
        --min-jaccard-similarity 0.4 \
--information-content-file  data/tmp/phenio_monarch_hp_mp_ic.tsv \
-O csv \
-o profiles/phenio-monarch-hp-mp.0.4.semsimian.ic.tsv
```

### Result:

| subject_id | subject_label                           | subject_source | object_id  | object_label                                        | object_source | ancestor_id | ancestor_label | ancestor_source | object_information_content | subject_information_content | ancestor_information_content | jaccard_similarity | cosine_similarity | dice_similarity | phenodigm_score |
|------------|-----------------------------------------|----------------|------------|-----------------------------------------------------|---------------|-------------|----------------|-----------------|----------------------------|-----------------------------|------------------------------|--------------------|-------------------|-----------------|-----------------|
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0008027 | abnormal spinal cord white matter morphology        | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0009686 | abnormal spinal cord medial motor column morphology | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0004250 | tau protein deposits                                | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0012260 | encephalomeningocele                                | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0009694 | abnormal spinal cord commissure morphology          | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0014066 | Rosenthal fibers                                    | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0002878 | abnormal corticospinal tract morphology             | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0000954 | decreased oligodendrocyte progenitor number         | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |
| HP:0006904 | Late-onset spinocerebellar degeneration | None           | MP:0020370 | abnormal glymphatic system morphology               | None          | owl:Thing   | None           | None            | None                       | None                        |                            0 |                  0 | None              | None            | None            |

### Command

```bash
runoak --stacktrace -vvv  -i semsimian:sqlite:data/ontology/phenio-monarch.db similarity -p i \
--set1-file data/tmp/hp_terms.txt \
--set2-file data/tmp/mp_terms.txt \
        --min-jaccard-similarity 0.4 \
-O csv \
-o profiles/phenio-monarch-hp-mp.0.4.semsimian.tsv
```

### Result

| subject_id | subject_label                                                     | subject_source | object_id  | object_label                                                | object_source | ancestor_id    | ancestor_label                      | ancestor_source | object_information_content | subject_information_content | ancestor_information_content | jaccard_similarity | cosine_similarity | dice_similarity | phenodigm_score    |
|------------|-------------------------------------------------------------------|----------------|------------|-------------------------------------------------------------|---------------|----------------|-------------------------------------|-----------------|----------------------------|-----------------------------|------------------------------|--------------------|-------------------|-----------------|--------------------|
| HP:0030080 | Burkitt lymphoma                                                  | None           | MP:0002396 | abnormal hematopoietic system morphology/development        | None          | UPHENO:0004459 | abnormal hematopoietic system       | None            | None                       | None                        |            5.816527256141925 | 0.4166666666666667 | None              | None            | 1.5567764847249168 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008591 | increased circulating interleukin-1 level                   | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008608 | increased circulating interleukin-13 level                  | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008602 | increased circulating interleukin-4 level                   | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0001754 | increased circulating corticotropin-releasing hormone level | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 | 0.4810126582278481 | None              | None            |  2.341460023490505 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008599 | increased circulating interleukin-2 level                   | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0002904 | increased circulating parathyroid hormone level             | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 | 0.4634146341463415 | None              | None            | 2.2982293510087612 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008626 | increased circulating interleukin-5 level                   | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |
| HP:0410194 | Increased uridine diphosphate glucose-4-epimerase level in plasma | None           | MP:0008635 | increased circulating interleukin-18 level                  | None          | UPHENO:0068533 | increased level of protein in blood | None            | None                       | None                        |           11.397693902282326 |  0.425531914893617 | None              | None            |  2.202290287770779 |

## Library Versions:
```
oaklib                        0.6.14
semsimian                     0.2.18
```

**Comment by matentzn** [comment] 2024-08-15 08:24
I moved this issue to the semsimian repo @souzadevinicius 

@justaddcoffee as this is of very high importance right now, can you see that someone is assigned to it? Thank you!

**Comment by justaddcoffee** [comment] 2024-08-15 12:33
@matentzn received, we will have a look at this as soon as we cna

**Comment by matentzn** [comment] 2024-08-15 12:37
Awesome, thank you!!

**Comment by caufieldjh** [comment] 2024-08-15 15:14
I tried to reproduce this - here's the command I used (with `phenio` instead of monarch phenio since I already had the former on hand)
```
$ runoak --stacktrace -vvv  -i semsimian:sqlite:obo:phenio similarity -p i --set1-file hp_terms.txt --set2-file mp_terms.txt --min-jaccard-similarity 0.4 --information-content-file phenio_monarch_hp_mp_ic.tsv
 -O csv -o phenio-monarch-hp-mp.0.4.semsimian.ic.tsv
```

I did notice one error from the beginning:
```
Loading custom IC map from: "phenio_monarch_hp_mp_ic.tsv"
Failed to import custom IC map: Error parsing IC value: invalid float literal
```
That happens because the header line isn't expected - and there's a fix to make that an actual error here: https://github.com/monarch-initiative/semsimian/pull/128

**Comment by justaddcoffee** [comment] 2024-08-15 15:20
@caufieldjh I'm not seeing that error on my end - can you confirm which version of semsimian and oak you are on?

**Comment by caufieldjh** [comment] 2024-08-15 15:21
oaklib                        0.6.14
semsimian                     0.2.16 <- yep, that's out of date

**Comment by justaddcoffee** [comment] 2024-08-15 15:22
I'm on 0.2.18, possibly it was fixed after 0.2.16:
```
(.venv) ~/PythonProject/issue133_semsimian_oak $ pip freeze | grep -E "oak|semsim" 
oaklib==0.6.14
semsimian==0.2.18
```

**Comment by caufieldjh** [comment] 2024-08-15 15:32
Yes, that was fixed in #132, so in practice the IC file should parse with or without a header.
(I'm still waiting on results from the above command)

**Comment by caufieldjh** [comment] 2024-08-15 19:58
OK, I see the same error - and *all* semsim values are zero:
```bash
$ cut -f12 phenio-monarch-hp-mp.0.4.semsimian.ic.tsv | uniq
ancestor_information_content
0
$ cut -f13 phenio-monarch-hp-mp.0.4.semsimian.ic.tsv | uniq
jaccard_similarity
0
```

**Comment by justaddcoffee** [comment] 2024-08-15 21:57
I can't seem to reproduce this error on my end. The lowest Jaccard similarity I'm seeing is 0.401234 (see below), although the run isn't done yet. In any case, not all 0s on my end.

I'm using these version of oaklib and semsimian:
```
oaklib                        0.6.14
semsimian                     0.2.18
```
the data files that @souzadevinicius provided here:
https://drive.google.com/drive/folders/1RWGhzHRtnBeJkLkSa0ldxOMldgGngVcS?usp=drive_link

and the version of phenio.db that I have on hand here from last year:
```
$ ls -lhd ~/.data/oaklib/phenio.db
-rw-r--r--  1 jtr4v  staff   8.1G Sep  6  2023 /Users/jtr4v/.data/oaklib/phenio.db
```

```
(.venv) ~/PythonProject/issue133_semsimian_oak $ pip freeze | grep -E "semsimian|oak" 
oaklib==0.6.14
semsimian==0.2.18
(.venv) ~/PythonProject/issue133_semsimian_oak $ runoak --stacktrace -vvv -i semsimian:sqlite:data/ontology/phenio.db similarity -p i --set1-file data/tmp/hp_terms.txt --set2-file data/tmp/mp_terms.txt --min-jaccard-similarity 0.4 --information-content-file data/tmp/phenio_monarch_hp_mp_ic.tsv -O csv -o phenio-monarch-hp-mp.0.4.semsimian.ic.tsv 

[[still running]]

(.venv) ~/PythonProject/issue133_semsimian_oak $ cut -f12 phenio-monarch-hp-mp.0.4.semsimian.ic.tsv | sort -n  | head -5
ancestor_information_content
4.129051805008942
4.129051805008942
4.129051805008942
4.129051805008942
(.venv) ~/PythonProject/issue133_semsimian_oak $ cut -f13 phenio-monarch-hp-mp.0.4.semsimian.ic.tsv | sort -n  | head -5
jaccard_similarity
0.4012345679012346
0.4012345679012346
0.4012345679012346
0.4012345679012346
```

Is this something to do with a newer version of Phenio that is confusing semsimian?

**Comment by caufieldjh** [comment] 2024-08-15 22:27
> Is this something to do with a newer version of Phenio that is confusing semsimian?

Possible - @souzadevinicius , do you know what version of PHENIO your `phenio-monarch.db` is built on?
I'm using a build from 2024-06-06.
There weren't any major technical changes for this release, though there is a newer build that hasn't made its way to semsql yet.
It's also interesting that it seems to work as expected when the `--information-content-file` isn't used, and even if there was something wrong with PHENIO, I would expect those zero-similarity values to be excluded by the filter.

I'm leaning toward this being some kind of uncaught parsing error.

**Comment by souzadevinicius** [comment] 2024-08-15 23:33
> > Is this something to do with a newer version of Phenio that is confusing semsimian?
> 
> Possible - @souzadevinicius , do you know what version of PHENIO your `phenio-monarch.db` is built on? I'm using a build from 2024-06-06. There weren't any major technical changes for this release, though there is a newer build that hasn't made its way to semsql yet. It's also interesting that it seems to work as expected when the `--information-content-file` isn't used, and even if there was something wrong with PHENIO, I would expect those zero-similarity values to be excluded by the filter.
> 
> I'm leaning toward this being some kind of uncaught parsing error.

I got it from the latest monarch-kg URL:

https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz

**Comment by justaddcoffee** [comment] 2024-08-16 11:35
I'm puzzled - I pulled the latest `phenio.db.gz` from here like this:
`wget https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz`

It looks a little smaller than @souzadevinicius, here's the size and md5sum unzipped:
```
(.venv) ~/PythonProject/issue133_semsimian_oak/data/ontology $ du -hsc phenio.db 
 11G    phenio.db
 11G    total
(.venv) ~/PythonProject/issue133_semsimian_oak/data/ontology $ md5sum phenio.db 
4e94fff3449d3c6aaba0cee5bcb2d2e1  phenio.db
```
but in any event it's the latest phenio from Monarch.

When I run that command again with the usual oak and semsimian versions:
```
(.venv) ~/PythonProject/issue133_semsimian_oak $ pip freeze | grep -E "semsimian|oak" 
oaklib==0.6.14
semsimian==0.2.18
```

like this:
```
runoak --stacktrace -i semsimian:sqlite:data/ontology/phenio.db similarity -p i --set1-file data/tmp/hp_terms.txt --set2-file data/tmp/mp_terms.txt --min-jaccard-similarity 0.4 --information-content-file data/tmp/phenio_monarch_hp_mp_ic.tsv -O csv -o phenio-monarch-hp-mp.0.4.semsimian.ic_PHENIO_MONARCH.tsv
```

I still get the correct `jaccard_similarity` and `ancestor_information_content` values:
```
(.venv) ~/PythonProject/issue133_semsimian_oak $  cut -f12 phenio-monarch-hp-mp.0.4.semsimian.ic_PHENIO_MONARCH.tsv | sort -n | head -5 
ancestor_information_content
4.129051805008942
4.129051805008942
4.129051805008942
4.129051805008942
(.venv) ~/PythonProject/issue133_semsimian_oak $  cut -f13 phenio-monarch-hp-mp.0.4.semsimian.ic_PHENIO_MONARCH.tsv | sort -n | head -5 
jaccard_similarity
0.40119760479041916
0.40119760479041916
0.40119760479041916
0.40119760479041916
```

@caufieldjh @souzadevinicius can you spot something I'm doing wrong/differently? 

Also, could you try to reproduce the steps I describe above? I.e. start with a fresh install, install those versions of oak and semsimian from pip, pull the latest phenio from Monarch, run the above command, and see if you still get the weird  `jaccard_similarity` and `ancestor_information_content` values?

**Comment by caufieldjh** [comment] 2024-08-16 14:15
Trying to reproduce again.
Latest phenio from monarch (https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz) has the same hash:
```
$ du -hsc phenio.db
12G     phenio.db
12G     total
$ md5sum phenio.db
4e94fff3449d3c6aaba0cee5bcb2d2e1  phenio.db
```
oaklib and semsimian versions are same as above.

(Will put results here once complete)

**Comment by souzadevinicius** [comment] 2024-08-16 14:59
> md5sum phenio.db

Same here:

~/monarch-semantic-similarity-profiles/data/ontology# md5sum phenio-monarch.db 
4e94fff3449d3c6aaba0cee5bcb2d2e1  phenio-monarch.db

**Comment by souzadevinicius** [comment] 2024-08-16 16:04
> @souzadevinicius @caufieldjh can you confirm which version of Python you are using?
> 
> I'm on python3.12 here
> 
> ```
> (.venv) ~/PythonProject/issue133_semsimian_oak $ python3 --version
> Python 3.12.3
> ```

Python from ODK Docker Image

Python 3.12.3

**Comment by justaddcoffee** [comment] 2024-08-16 16:07
Okay, thanks - which operating system and version?

**Comment by souzadevinicius** [comment] 2024-08-16 16:22
> Okay, thanks @souzadevinicius - which operating system and version?

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by caufieldjh** [comment] 2024-08-16 20:06
Hi @souzadevinicius , we think this is due to some weirdness in how Semsimian is handling information content files without the full set of ancestors.
In your IC file, for example, you have only HP and MP nodes, but Semsimian also expects to find IC values for common ancestors like UPHENO.
The resulting zero values aren't informative so we're working on a fix.

In the meantime, try using an IC file including HP, MP, _and_ ancestors of each in PHENIO (yes, in practice this will be most of PHENIO) - something like this should work:
```
runoak -i sqlite:phenio.db information-content -p i .all > phenio_ic.tsv
```

**Comment by souzadevinicius** [comment] 2024-08-17 00:56
> Hi @souzadevinicius , we think this is due to some weirdness in how Semsimian is handling information content files without the full set of ancestors. In your IC file, for example, you have only HP and MP nodes, but Semsimian also expects to find IC values for common ancestors like UPHENO. The resulting zero values aren't informative so we're working on a fix.
> 
> In the meantime, try using an IC file including HP, MP, _and_ ancestors of each in PHENIO (yes, in practice this will be most of PHENIO) - something like this should work:
> 
> ```
> runoak -i sqlite:phenio.db information-content -p i .all > phenio_ic.tsv
> ```

OK, @caufieldjh , thank you so far.

**Comment by hrshdhgd** [comment] 2024-08-19 16:47
Alright @souzadevinicius ... I think I may have figured this out .... In your command line drop the `-p i` and rerun it. That was causing the problem.

**Comment by souzadevinicius** [comment] 2024-08-19 17:09
> Alright @souzadevinicius ... I think I may have figured this out .... In your command line drop the `-p i` and rerun it. That was causing the problem. Not sure if this is need or no.

OK, @hrshdhgd, I can try running the command without the `-p`, but could you provide more details about this problem? 
Did I make a mistake during command line construction? 
Why did it happen?

**Comment by hrshdhgd** [comment] 2024-08-19 18:28
That is something I'm trying to find out ... you did not do anything wrong. You followed the documentation. I think the reason is [Harry's comment](https://github.com/monarch-initiative/semsimian/issues/133#issuecomment-2294159008) above.

**Comment by hrshdhgd** [comment] 2024-08-19 18:50
Bug in `oaklib` .... fixing it: https://github.com/INCATools/ontology-access-kit/pull/800

**Closed** 2024-08-20 20:44 UTC

**Comment by hrshdhgd** [comment] 2024-08-20 20:58
`oaklib v0.6.16` should fix this issue.
